### ISSUE TITLE
Team Project Plan

### ISSUE THREAD

**Issue by johnoliver42** [johnoliver42/team-enterprise#1]
@pawaitemadisoncollege

We have completed our team resume, charter, problem statement, etc.

**Comment by pawaitemadisoncollege** [comment]
Hi @johnoliver42 @eburzlaff @fchristian1992 @eemclaughlin!

Your team charter and resume are well done! 

**Problem statement:** "Create a library management system". Remember **you are creating a restful api**, not a web application like in your indie project. Your work should be very much like the week 9 exercise.

- [ ] A good next step is to detail in your README.md what resources your RESTful API will provide, what operations your RESTful API will support, and what filters a caller might use.  For example:

Resource: books, Operations: GET, POST
Resource: users, Operations: GET, POST

Then... what "filters" will these support? Meaning how will a caller retrieve books? By id, title, something else? Same question for User. 

**Let me know when that is ready for review, so that we are all on the same page. Thanks!** 

**Other items to address:** 

- [ ] How will you manage work in git? Feature branches? 
- [ ] You did a nice job laying out many of the task to complete for this project. A few that seem to be missing 

- document the restful resources and operations that your service will support.
- create the service classes that will provide responses to api consumers, or was this included under the "controller" task
- create the user guide; consider using Swagger for this - see Austin's prof dev presentation this week for more info
- create the final presentation - I would expect each of you to be part of this
- unit test pojo-daos (essentially one dao unit test per table)

- [ ] In week 7 I demonstrated how to use cognito for auth for web applications, and you practiced with this in the exercise that week. Remember that you are building a restful api, so you'll be using cognito in a slightly different way if you do attempt this stretch goal. More info here: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html
